In [1]:
import os
import sys
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import glob

In [29]:
# directories
datadir='/data1/adac/'
llc4320dir=datadir + 'mitgcm/regions/'
processdir=datadir + 'process/'

REGION='WesternMed'
regiondir=llc4320dir+REGION+'/'
griddir=regiondir+'grid/'

<generator object walk at 0x7f42bd0b73c0>

In [60]:
# get grid info
xcf=glob.glob(griddir + 'XC*')
# print(xcf)
import fnmatch
fnmatch(xcf,'XC*')

# str.find(xcf,'XC_')

TypeError: 'module' object is not callable

In [65]:
# load theta and salt
# for thisvar in ['Salt','Theta']:
for thisvar in ['Salt']:
    thisdir = regiondir + thisvar
    for files in os.scandir(thisdir):
        fn = thisdir + files.name
        # get time from name: timesteps are 25-sec, since sept 9, 2011
        timedelta=np.int(files.name[0:10])*25
        timedelta=496800*25
        tref=np.datetime64('2011-09-09')
        thist=tref + np.timedelta64(timedelta,'s')
        print(thist)
        # get 
        
    
fns=regiondir+'Salt/'+'0000010368_Salt_1873.9965.1_192.265.76'
nx=192
ny=265
nz=76
# 

# s=np.memmap(fns,'>f4',mode='r')
# s=np.memmap(fns,'>f4',mode='r',shape=(nz,nx,ny))


# Load theta and salt data from fnt, fns
#      Calculate density and steric height at each level integrated from the surface z=0
#      Note that the free surface Eta is not included in the calculation. 

#      Parameter: 
#      fnt: the file name of theta
#      fns: the file name of salt

#     """

#     s=np.memmap(fns,'>f4',mode='r',shape=(nz,nxy))
#     t=np.memmap(fnt,'>f4',mode='r',shape=(nz,nxy))
#     dens=popy.jmd95.densjmd95(s,t,pres)


2012-01-30T18:00:00
2012-01-30T18:00:00
2012-01-30T18:00:00
2012-01-30T18:00:00
2012-01-30T18:00:00


In [4]:
print(s.shape)
zi=0
ssub=s[zi,:,:]
print(ssub.shape)
print(ssub)

(76, 192, 265)
(192, 265)
[[36.603245 36.60481  36.59754  ...  0.        0.        0.      ]
 [ 0.        0.        0.       ...  0.        0.        0.      ]
 [ 0.        0.        0.       ... 36.592995 36.591145 36.58882 ]
 ...
 [37.526783 37.504745 37.462467 ... 37.70333  37.695423 37.689846]
 [37.68605  37.68328  37.681507 ... 37.61721  37.620544 37.622074]
 [37.62132  37.618286 37.612495 ... 37.47581  37.474304 37.471447]]


In [5]:
%matplotlib inline
# plot one level
zi=0
plt.figure(figsize=(10,10))
ax1=plt.subplot(2,2,1)
plt.subplots_adjust(hspace=0.1)
# ax1.coastlines('50m')
dpts=10
cb=ax1.pcolor(s[zi,:,:])
#                    c=data_std[vpl][::ipl],marker='.',vmin=0,vmax=0.2)
#     plt.colorbar(cb,fraction=0.046, pad=0.04, shrink=.5)
#     plt.title(r'$\sigma_%s$' % vpl)
plt.show()

ValueError: magics not found

{'commit_hash': '223e783c4',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/home/kdrushka/miniconda3/envs/py37/lib/python3.8/site-packages/IPython',
 'ipython_version': '7.19.0',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-130-generic-x86_64-with-glibc2.10',
 'sys_executable': '/home/kdrushka/miniconda3/envs/py37/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.8.6 | packaged by conda-forge | (default, Oct  7 2020, '
                '19:20:40) \n'
                '[GCC 7.5.0]'}
